### ISSUE TITLE
After creating the vm estabilishing the connection fails

### ISSUE THREAD

**Issue by akhiljns** [mhewedy/vermin#46]
the vm has been created and i can see it running but on performing ssh into the VM it throws following logs

```
yscall.GetFileAttributesEx(0xc008d5e840?, 0x0, 0x0?)
        C:/Program Files/Go/src/syscall/zsyscall_windows.go:750 +0x65 fp=0xc0054258e8 sp=0xc005425898 pc=0x74be65
os.stat({0xac790a, 0x4}, {0xc008d5e840, 0x29}, 0x1)
        C:/Program Files/Go/src/os/stat_windows.go:35 +0x289 fp=0xc005425c38 sp=0xc0054258e8 pc=0x77c849
os.statNolog(...)
        C:/Program Files/Go/src/os/stat_windows.go:121
os.Stat({0xc008d5e840, 0x29})
        C:/Program Files/Go/src/os/stat.go:13 +0x3d fp=0xc005425c70 sp=0xc005425c38 pc=0x77c4dd
os/exec.chkStat({0xc008d5e840?, 0xc002b13040?})
        C:/Program Files/Go/src/os/exec/lp_windows.go:20 +0x18 fp=0xc005425c90 sp=0xc005425c70 pc=0x990f98
os/exec.findExecutable({0xc002b13040, 0x25}, {0xc004480b00, 0xb, 0xa44120?})
        C:/Program Files/Go/src/os/exec/lp_windows.go:48 +0xd6 fp=0xc005425ce8 sp=0xc005425c90 pc=0x991176
os/exec.LookPath({0xac9a96, 0xa})
        C:/Program Files/Go/src/os/exec/lp_windows.go:115 +0x49c fp=0xc005425e58 sp=0xc005425ce8 pc=0x99169c
os/exec.Command({0xac9a96, 0xa}, {0xc007645da0, 0x6, 0xa44120?})
        C:/Program Files/Go/src/os/exec/exec.go:419 +0x217 fp=0xc005425ee8 sp=0xc005425e58 pc=0x98c7b7
github.com/mhewedy/vermin/cmd.(*Cmd).Run(0xc005425f90)
        D:/programs/vermin/cmd/cmd.go:93 +0x170 fp=0xc005425f58 sp=0xc005425ee8 pc=0x992dd0
github.com/mhewedy/vermin/ip.ping.func1(0x0?)
        D:/programs/vermin/ip/ping.go:26 +0x114 fp=0xc005425fc8 sp=0xc005425f58 pc=0x998fd4
github.com/mhewedy/vermin/ip.ping.func2()
        D:/programs/vermin/ip/ping.go:28 +0x27 fp=0xc005425fe0 sp=0xc005425fc8 pc=0x998e87
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc005425fe8 sp=0xc005425fe0 pc=0x6fad21
created by github.com/mhewedy/vermin/ip.ping in goroutine 1
        D:/programs/vermin/ip/ping.go:25 +0x98

goroutine 6700 [runnable, locked to thread]:
runtime.cgocall(0x6fc4e0, 0xc0077b7ac8)
        C:/Program Files/Go/src/runtime/cgocall.go:157 +0x3e fp=0xc00542f7d8 sp=0xc00542f7a0 pc=0x69817e
syscall.SyscallN(0x7ffee9600650?, {0xc00542f870?, 0x3?, 0x0?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:544 +0x107 fp=0xc00542f850 sp=0xc00542f7d8 pc=0x6f7aa7
syscall.Syscall(0x29?, 0xc008f3d9e0?, 0xffffffffffffffff?, 0xc00542f8d8?, 0x6a0aa5?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:482 +0x35 fp=0xc00542f898 sp=0xc00542f850 pc=0x6f77f5
syscall.GetFileAttributesEx(0xc008fc01e0?, 0x0, 0x0?)
        C:/Program Files/Go/src/syscall/zsyscall_windows.go:750 +0x65 fp=0xc00542f8e8 sp=0xc00542f898 pc=0x74be65
os.stat({0xac790a, 0x4}, {0xc008fc01e0, 0x29}, 0x1)
        C:/Program Files/Go/src/os/stat_windows.go:35 +0x289 fp=0xc00542fc38 sp=0xc00542f8e8 pc=0x77c849
os.statNolog(...)
        C:/Program Files/Go/src/os/stat_windows.go:121
os.Stat({0xc008fc01e0, 0x29})
        C:/Program Files/Go/src/os/stat.go:13 +0x3d fp=0xc00542fc70 sp=0xc00542fc38 pc=0x77c4dd
os/exec.chkStat({0xc008fc01e0?, 0xc0041f3d80?})
        C:/Program Files/Go/src/os/exec/lp_windows.go:20 +0x18 fp=0xc00542fc90 sp=0xc00542fc70 pc=0x990f98
os/exec.findExecutable({0xc0041f3d80, 0x25}, {0xc003ec5c00, 0xb, 0xa44120?})
        C:/Program Files/Go/src/os/exec/lp_windows.go:48 +0xd6 fp=0xc00542fce8 sp=0xc00542fc90 pc=0x991176
os/exec.LookPath({0xac9a96, 0xa})
        C:/Program Files/Go/src/os/exec/lp_windows.go:115 +0x49c fp=0xc00542fe58 sp=0xc00542fce8 pc=0x99169c
os/exec.Command({0xac9a96, 0xa}, {0xc007f9b8c0, 0x6, 0xa44120?})
        C:/Program Files/Go/src/os/exec/exec.go:419 +0x217 fp=0xc00542fee8 sp=0xc00542fe58 pc=0x98c7b7
github.com/mhewedy/vermin/cmd.(*Cmd).Run(0xc00542ff90)
        D:/programs/vermin/cmd/cmd.go:93 +0x170 fp=0xc00542ff58 sp=0xc00542fee8 pc=0x992dd0
github.com/mhewedy/vermin/ip.ping.func1(0x0?)
        D:/programs/vermin/ip/ping.go:26 +0x114 fp=0xc00542ffc8 sp=0xc00542ff58 pc=0x998fd4
github.com/mhewedy/vermin/ip.ping.func2()
        D:/programs/vermin/ip/ping.go:28 +0x27 fp=0xc00542ffe0 sp=0xc00542ffc8 pc=0x998e87
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00542ffe8 sp=0xc00542ffe0 pc=0x6fad21
created by github.com/mhewedy/vermin/ip.ping in goroutine 1
        D:/programs/vermin/ip/ping.go:25 +0x98

goroutine 6701 [runnable, locked to thread]:
runtime.cgocall(0x6fc4e0, 0xc0077cc2c8)
        C:/Program Files/Go/src/runtime/cgocall.go:157 +0x3e fp=0xc0054217d8 sp=0xc0054217a0 pc=0x69817e
syscall.SyscallN(0x7ffee9600650?, {0xc005421870?, 0x3?, 0x0?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:544 +0x107 fp=0xc005421850 sp=0xc0054217d8 pc=0x6f7aa7
syscall.Syscall(0x29?, 0xc008f3daa0?, 0xffffffffffffffff?, 0xc0054218d8?, 0x6a0aa5?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:482 +0x35 fp=0xc005421898 sp=0xc005421850 pc=0x6f77f5
syscall.GetFileAttributesEx(0xc008fc0240?, 0x0, 0x0?)
        C:/Program Files/Go/src/syscall/zsyscall_windows.go:750 +0x65 fp=0xc0054218e8 sp=0xc005421898 pc=0x74be65
os.stat({0xac790a, 0x4}, {0xc008fc0240, 0x29}, 0x1)
        C:/Program Files/Go/src/os/stat_windows.go:35 +0x289 fp=0xc005421c38 sp=0xc0054218e8 pc=0x77c849
os.statNolog(...)
        C:/Program Files/Go/src/os/stat_windows.go:121
os.Stat({0xc008fc0240, 0x29})
        C:/Program Files/Go/src/os/stat.go:13 +0x3d fp=0xc005421c70 sp=0xc005421c38 pc=0x77c4dd
os/exec.chkStat({0xc008fc0240?, 0xc000cf4ac0?})
        C:/Program Files/Go/src/os/exec/lp_windows.go:20 +0x18 fp=0xc005421c90 sp=0xc005421c70 pc=0x990f98
os/exec.findExecutable({0xc000cf4ac0, 0x25}, {0xc00235e400, 0xb, 0xa44120?})
        C:/Program Files/Go/src/os/exec/lp_windows.go:48 +0xd6 fp=0xc005421ce8 sp=0xc005421c90 pc=0x991176
os/exec.LookPath({0xac9a96, 0xa})
        C:/Program Files/Go/src/os/exec/lp_windows.go:115 +0x49c fp=0xc005421e58 sp=0xc005421ce8 pc=0x99169c
os/exec.Command({0xac9a96, 0xa}, {0xc007f9b920, 0x6, 0xa44120?})
        C:/Program Files/Go/src/os/exec/exec.go:419 +0x217 fp=0xc005421ee8 sp=0xc005421e58 pc=0x98c7b7
github.com/mhewedy/vermin/cmd.(*Cmd).Run(0xc005421f90)
        D:/programs/vermin/cmd/cmd.go:93 +0x170 fp=0xc005421f58 sp=0xc005421ee8 pc=0x992dd0
github.com/mhewedy/vermin/ip.ping.func1(0x0?)
        D:/programs/vermin/ip/ping.go:26 +0x114 fp=0xc005421fc8 sp=0xc005421f58 pc=0x998fd4
github.com/mhewedy/vermin/ip.ping.func2()
        D:/programs/vermin/ip/ping.go:28 +0x27 fp=0xc005421fe0 sp=0xc005421fc8 pc=0x998e87
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc005421fe8 sp=0xc005421fe0 pc=0x6fad21
created by github.com/mhewedy/vermin/ip.ping in goroutine 1
        D:/programs/vermin/ip/ping.go:25 +0x98

goroutine 6702 [runnable, locked to thread]:
runtime.cgocall(0x6fc4e0, 0xc0044646c8)
        C:/Program Files/Go/src/runtime/cgocall.go:157 +0x3e fp=0xc00542b7d8 sp=0xc00542b7a0 pc=0x69817e
syscall.SyscallN(0x7ffee9600650?, {0xc00542b870?, 0x3?, 0x0?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:544 +0x107 fp=0xc00542b850 sp=0xc00542b7d8 pc=0x6f7aa7
syscall.Syscall(0x29?, 0xc008e43740?, 0xffffffffffffffff?, 0xc00542b8d8?, 0x6a0aa5?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:482 +0x35 fp=0xc00542b898 sp=0xc00542b850 pc=0x6f77f5
syscall.GetFileAttributesEx(0xc008cd8b70?, 0x0, 0x0?)
        C:/Program Files/Go/src/syscall/zsyscall_windows.go:750 +0x65 fp=0xc00542b8e8 sp=0xc00542b898 pc=0x74be65
os.stat({0xac790a, 0x4}, {0xc008cd8b70, 0x29}, 0x1)
        C:/Program Files/Go/src/os/stat_windows.go:35 +0x289 fp=0xc00542bc38 sp=0xc00542b8e8 pc=0x77c849
os.statNolog(...)
        C:/Program Files/Go/src/os/stat_windows.go:121
os.Stat({0xc008cd8b70, 0x29})
        C:/Program Files/Go/src/os/stat.go:13 +0x3d fp=0xc00542bc70 sp=0xc00542bc38 pc=0x77c4dd
os/exec.chkStat({0xc008cd8b70?, 0xc003ff6740?})
        C:/Program Files/Go/src/os/exec/lp_windows.go:20 +0x18 fp=0xc00542bc90 sp=0xc00542bc70 pc=0x990f98
os/exec.findExecutable({0xc003ff6740, 0x25}, {0xc004120f00, 0xb, 0xa44120?})
        C:/Program Files/Go/src/os/exec/lp_windows.go:48 +0xd6 fp=0xc00542bce8 sp=0xc00542bc90 pc=0x991176
os/exec.LookPath({0xac9a96, 0xa})
        C:/Program Files/Go/src/os/exec/lp_windows.go:115 +0x49c fp=0xc00542be58 sp=0xc00542bce8 pc=0x99169c
os/exec.Command({0xac9a96, 0xa}, {0xc000d88720, 0x6, 0xa44120?})
        C:/Program Files/Go/src/os/exec/exec.go:419 +0x217 fp=0xc00542bee8 sp=0xc00542be58 pc=0x98c7b7
github.com/mhewedy/vermin/cmd.(*Cmd).Run(0xc00542bf90)
        D:/programs/vermin/cmd/cmd.go:93 +0x170 fp=0xc00542bf58 sp=0xc00542bee8 pc=0x992dd0
github.com/mhewedy/vermin/ip.ping.func1(0x0?)
        D:/programs/vermin/ip/ping.go:26 +0x114 fp=0xc00542bfc8 sp=0xc00542bf58 pc=0x998fd4
github.com/mhewedy/vermin/ip.ping.func2()
        D:/programs/vermin/ip/ping.go:28 +0x27 fp=0xc00542bfe0 sp=0xc00542bfc8 pc=0x998e87
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00542bfe8 sp=0xc00542bfe0 pc=0x6fad21
created by github.com/mhewedy/vermin/ip.ping in goroutine 1
        D:/programs/vermin/ip/ping.go:25 +0x98
    .............
```

PS : _this is just a part of infinite logs that i keeps generating_

**Comment by akhiljns** [comment]
![Screenshot 2024-03-20 221508](https://github.com/mhewedy/vermin/assets/22194681/7348fb0e-343f-490e-bbe0-1fa776d5256d)

@mhewedy  this function seems to be spawning 65535 goroutines 

what exactly are you trying to do here? 

```
ipAddr, err := ip.Find(vmName, false)
	if err != nil {
		return err
	}

	return cmd.Ssh(ipAddr, "-tt").Interact()
```

seems like this particular code is trying to ping every ip in that subnet and checking which ip address returns a pong (but if I am wrong then please correct me here)

can't we define a constant ip address before starting the vm and assign that ip to inbound connections to that VM?

**Comment by mhewedy** [comment]
@akhiljns 

yes, your ananlysis is correct.

I am not sure about defining a static IP address. 

but I see ppl facing troubles with bridge network so I opened this issue to record this https://github.com/mhewedy/vermin/issues/33 (may be to use NAT such as vagrant)

**Comment by akhiljns** [comment]
@mhewedy Alright then I'm going to research about this a bit and then do this myself

**Comment by akhiljns** [comment]
> @akhiljns
> 
> yes, your ananlysis is correct.
> 
> I am not sure about defining a static IP address.
> 
> but I see ppl facing troubles with bridge network so I opened this issue to record this #33 (may be to use NAT such as vagrant)

Ok so finally I have some time to start looking deeper into this project. Really interesting project that you've built here. I'm going to work on this a lot now.

I have 3 points to mention

1) So for now Essentially this project is a wrapper on top of virtualbox VBoxManage commands (unless another hypervisor is added), I don't think it is the problem of bridged network, it seems to be the problem of not being able to find the ip address of the created vm, it either spawns many goroutines, spike the goroutine count and results in memory leakage OR maybe its just not finding the ip
: to solve this maybe we should try assigning an ip address to the created vm since to ssh into the box we need to provide a static ip to the box, let me see if I can assign a static ip using VBoxManage

2) If we can't provide static ip address then there should be a way to get the ip address of the vm after creating it like maybe VBoxManage import command or startvm command returns ip address which we can use to ssh directly

3) We should add another hypervisor to really make this project interesting like qemu since it has good support for commandline commands and is very light to be managed by vermin

**Comment by mhewedy** [comment]
BTW, I had this short conversation with chatgpt where it suggests to use dhcp client to try to discover the ip address, you can find it here

https://chat.openai.com/c/643b8c00-a487-44b4-8007-1ae39d42e25d

**Comment by akhiljns** [comment]
> BTW, I had this short conversation with chatgpt where it suggests to use dhcp client to try to discover the ip address, you can find it here
> 
> https://chat.openai.com/share/fe7b9f6c-9f91-42e4-bd32-4410596f9485

I'm going to add qemu as the next hypervisor after I figure out this network issue, I'm still keen on using bridged network because that way we can actually truly simulate a cluster since we will get vm<->vm communication and also LAN connection which is essential if I have lets say a database server and a application server in the same cluster. Using NAT with port forwarding would also allow us to do this I think, but i'll give this a try

So, I looked at the chatgpt code but sadly that does not work the dhcp client it uses doesn't have the functions it's using. but I have an interesting workaround

If I provide the same MAC address to the vm then it will get same ip address as the host so maybe we can do this and then ssh into the vm and then provide a static ip address there

**Comment by mhewedy** [comment]
I didn't got this part

> If I provide the same MAC address to the vm then it will get same ip address as the host so maybe we can do this and then ssh into the vm and then provide a static ip address there, this is just a thinking for now, i'm trying this, i'll share my findings

I did some quick research for a reliable way to discover IPs in the network, and I see ppl referring to nmap maybe? as ARP (the currently used technique in vermin) returns the cache of usage in case there was a connection between the current machine and the target IP

**Comment by akhiljns** [comment]
@mhewedy I actually solved this using GetVmProperty command i was surprised to know that virtualbox developers themselves didn't know about this but turns out you can get the ip address of the started vm,

raising a pr

**Comment by mhewedy** [comment]
> 3. We should add another hypervisor to really make this project interesting like qemu since it has good support for commandline commands and is very light to be managed by vermin

I think libvert might be a better option. as it is higher level than qemu and it utilizes qemu and KVM already.

**Comment by akhiljns** [comment]
> > 3. We should add another hypervisor to really make this project interesting like qemu since it has good support for commandline commands and is very light to be managed by vermin
> 
> I think libvert might be a better option. as it is higher level than qemu and it utilizes qemu and KVM already.

oh yeah I've heard about libvert but never used it, let me look into it
